# ============================================
# secret.yml — Credenciales de Postgres
# Los valores son base64 de los strings reales
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-portfolio
type: Opaque
data:
  POSTGRES_USER:     cG9zdGdyZXM=      # "postgres"
  POSTGRES_PASSWORD: ZGV2b3BzMTIz      # "devops123"
  POSTGRES_DB:       bm90ZXNkYg==      # "notesdb"
